insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '10140', 'NextGen File', '10140o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '93922', 'NextGen File', '93922o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11719', 'NextGen File', '11719o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11720', 'NextGen File', '11720o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11721', 'NextGen File', '11721o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11055', 'NextGen File', '11055o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11056', 'NextGen File', '11056o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11057', 'NextGen File', '11057o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11060', 'NextGen File', '11060o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11061', 'NextGen File', '11061o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '10160', 'NextGen File', '10160o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11730', 'NextGen File', '11730o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11732', 'NextGen File', '11732o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11740', 'NextGen File', '11740o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11750', 'NextGen File', '11750o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11040', 'NextGen File', '11040o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11042', 'NextGen File', '11042o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11043', 'NextGen File', '11043o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11045', 'NextGen File', '11045o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11046', 'NextGen File', '11046o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '97598', 'NextGen File', '97598o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '17110', 'NextGen File', '17110o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11755', 'NextGen File', '11755o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '11765', 'NextGen File', '11765o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '20605', 'NextGen File', '20605o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '20600', 'NextGen File', '20600o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '20550', 'NextGen File', '20550o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '64450', 'NextGen File', '64450o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '29540', 'NextGen File', '29540o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '29550', 'NextGen File', '29550o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '76000', 'NextGen File', '76000o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '76881', 'NextGen File', '76881o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '76882', 'NextGen File', '76882o', '16', '16', SYSDATETIME(), SYSDATETIME())
insert into macro_trans (macro_id, field_value, result_type, result_key, created_by, modified_by, create_timestamp, modify_timestamp)
values ('41233', '76942', 'NextGen File', '76942o', '16', '16', SYSDATETIME(), SYSDATETIME())
